/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "rfe-light-btn": "var(--light-btn)",
        "rfe-surface": "var(--surface)",
        "rfe-surface-dim": "var(--surface-dim)",
        "rfe-surface-bright": "var(--surface-bright)",
        "rfe-surface-container-lowest": "var(--surface-container-lowest)",
        "rfe-surface-container-lowest-opacity":
          "var(--surface-container-lowest-opacity)",
        "rfe-surface-container-low": "var(--surface-container-low)",
        "rfe-surface-container": "var(--surface-container)",
        "rfe-surface-container-high": "var(--surface-container-high)",
        "rfe-surface-container-highest": "var(--surface-container-highest)",
        "rfe-on-surface": "var(--on-surface)",
        "rfe-on-surface-variant": "var(--on-surface-variant)",
        "rfe-inverse-surface": "var(--inverse-surface)",
        "rfe-inverse-on-surface": "var(--inverse-on-surface)",
        "rfe-outline": "var(--outline)",
        "rfe-outline-variant": "var(--outline-variant)",
        "rfe-surface-tint": "var(--surface-tint)",
        "rfe-primary": "var(--primary)",
        "rfe-on-primary": "var(--on-primary)",
        "rfe-primary-container": "var(--primary-container)",
        "rfe-on-primary-container": "var(--on-primary-container)",
        "rfe-inverse-primary": "var(--inverse-primary)",
        "rfe-secondary": "var(--secondary)",
        "rfe-on-secondary": "var(--on-secondary)",
        "rfe-secondary-container": "var(--secondary-container)",
        "rfe-on-secondary-container": "var(--on-secondary-container)",
        "rfe-tertiary": "var(--tertiary)",
        "rfe-on-tertiary": "var(--on-tertiary)",
        "rfe-tertiary-container": "var(--tertiary-container)",
        "rfe-on-tertiary-container": "var(--on-tertiary-container)",
        "rfe-error": "var(--error)",
        "rfe-on-error": "var(--on-error)",
        "rfe-error-container": "var(--error-container)",
        "rfe-on-error-container": "var(--on-error-container)",
        "rfe-primary-fixed": "var(--primary-fixed)",
        "rfe-primary-fixed-dim": "var(--primary-fixed-dim)",
        "rfe-on-primary-fixed": "var(--on-primary-fixed)",
        "rfe-on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "rfe-secondary-fixed": "var(--secondary-fixed)",
        "rfe-secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "rfe-on-secondary-fixed": "var(--on-secondary-fixed)",
        "rfe-on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "rfe-tertiary-fixed": "var(--tertiary-fixed)",
        "rfe-tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "rfe-on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "rfe-on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "rfe-background": "var(--background)",
        "rfe-on-background": "var(--on-background)",
        "rfe-surface-variant": "var(--surface-variant)",
        "rfe-title-pink": "var(--title-pink)",
      },
      "borderRadius": {
        "rfe-radius-base": "var(--radius-base)",
      },
      screens: {
        "xs": "475px",
        "3xl": "1920px",
      },
    },
  },
  plugins: [],
};
